<a href="https://colab.research.google.com/github/Esteyak00170/DAV/blob/main/basics_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])

In [3]:
print("1D Array:")

1D Array:


In [4]:
print("Shape:", arr_1d.shape)

Shape: (5,)


In [5]:
print("Size:", arr_1d.size)

Size: 5


In [6]:
print("Dimension:", arr_1d.ndim)

Dimension: 1


In [7]:
print("Length:", len(arr_1d))
print()

Length: 5



In [9]:
print("2D Array:")
print("Shape:", arr_2d.shape)
print("Size:", arr_2d.size)
print("Dimension:", arr_2d.ndim)
print("Length:", len(arr_2d))
print()

2D Array:
Shape: (3, 3)
Size: 9
Dimension: 2
Length: 3



In [10]:
print("3D Array:")
print("Shape:", arr_3d.shape)
print("Size:", arr_3d.size)
print("Dimension:", arr_3d.ndim)
print("Length:", len(arr_3d))
print()

3D Array:
Shape: (2, 2, 3)
Size: 12
Dimension: 3
Length: 2



In [21]:
print("Examples of array creation functions:")

Examples of array creation functions:


In [12]:
print("np.arange(5):", np.arange(5))
print("np.random.randint(1, 10, size=(2, 3)):")

np.arange(5): [0 1 2 3 4]
np.random.randint(1, 10, size=(2, 3)):


In [13]:
print(np.random.randint(1, 10, size=(2, 3)))

[[5 7 5]
 [2 8 4]]


In [16]:
print("np.random.rand(2, 3):")
print(np.random.rand(2, 3))

np.random.rand(2, 3):
[[0.49536389 0.01974843 0.27560971]
 [0.35701403 0.54112917 0.28761599]]


In [17]:
print("np.linspace(0, 10, 5):", np.linspace(0, 10, 5))
print("np.ones((2, 3)):")

np.linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]
np.ones((2, 3)):


In [18]:
print(np.ones((2, 3)))
print("np.zeros((2, 3)):")

[[1. 1. 1.]
 [1. 1. 1.]]
np.zeros((2, 3)):


In [19]:
print(np.zeros((2, 3)))
print("np.diag([1, 2, 3]):")

[[0. 0. 0.]
 [0. 0. 0.]]
np.diag([1, 2, 3]):


In [20]:
print(np.diag([1, 2, 3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
